const OrderPizza=require("../Locators/PizzaOrder.json")
export class PizzaOrder{
    PizzaSelection1(){
        cy.xpath(OrderPizza.PizzaSelection.Pizza_Selection).scrollIntoView().click()
        cy.wait(600)
        return
    }
    PizzaSelection2(){
        cy.xpath(OrderPizza.PizzaSelection.Pizza_Selection2).click()
        cy.wait(300)
        return
    }
    PizzaSize(){
        cy.xpath(OrderPizza.PizzaSelection.PizzaSize).scrollIntoView().click()
        cy.wait(1000)
        return
    }
    FirstTenPizza(){
        cy.xpath(OrderPizza.PizzaSelection.SelectFirstTenPizza).scrollIntoView().click()
        cy.wait(800)
        return
    }
    SecondTenPizza(){
        cy.xpath(OrderPizza.PizzaSelection.SelectSecondTenPizza).scrollIntoView().click()
        cy.wait(800)
        return
    }
    SelectCheese(){
        cy.xpath(OrderPizza.PizzaSelection.SelectCheese).scrollIntoView().click()
        cy.wait(800)
        return
    }
    AddToCart(){
        cy.xpath(OrderPizza.PizzaSelection.AddToCart).scrollIntoView().click()
        cy.wait(800)
        return
    }
    SelectQuantity(){
        cy.get('#quantity_6669b14573060').clear().type('2')
        cy.wait(300)
        return
    }
    ViewBasket(){
        cy.xpath(OrderPizza.PizzaSelection.ViewBasket).scrollIntoView().click()
        cy.wait(800)
        return
    }
    ProceedToCheckOut(){
        cy.xpath(OrderPizza.PizzaSelection.ProceedToCheckOut).scrollIntoView().click()
        cy.wait(800)
        return
    }
}